USE `agedle`;

INSERT INTO `civs` VALUES 
	(1, 'Armenians', 'Infantry Naval', 'The mountain Royals', 'No', 'Infantry Archer', 'Yes', 'Mediterranean', 'No'),
    (2, 'Aztecs', 'Infantry Monk', 'The conquerors', 'No', 'Infantry', 'Yes', 'Mesoamerican', 'No'),
    (3, 'Bengalis', 'Cavalry Naval', 'Dynasties of India', 'No', 'MountedArcher', 'Yes', 'South Asian', 'Yes'),
    (4, 'Berbers', 'Cavalry Naval', 'The african kingdoms', 'Yes', 'MountedArcher MountedSkirmisher', 'Yes', 'Middle Eastern', 'Yes'),
    (5, 'Bohemians', 'Gunpowder Monk', 'Dawn of the dukes', 'No', 'Siege Gunpowder', 'Yes', 'Eastern European', 'Yes'),
    (6, 'Britons', 'Archer', 'The age of Kings', 'Yes', 'Archer', 'No', 'Western European', 'Yes'),
    (7, 'Bulgarians', 'Infantry Cavalry', 'The last khans', 'No', 'Cavalry', 'Yes', 'Eastern European', 'Yes'),
    (8, 'Burgundians', 'Cavalry', 'Lords of the west', 'No', 'Cavalry', 'Yes', 'Western European', 'Yes'),
    (9, 'Burmese', 'Infantry Cavalry', 'Rise of the rajas', 'No', 'MountedArcher', 'Yes', 'Southeast Asian', 'Yes'),
    (10, 'Byzantines', 'Defensive', 'The age of Kings', 'No', 'Cavalry', 'Yes', 'Mediterranean', 'No'),
    (11, 'Celts', 'Infantry Siege', 'The age of Kings', 'No', 'Infantry', 'No', 'Western European', 'Yes'),
    (12, 'Chinese', 'Archer Gunpowder', 'The age of Kings', 'Yes', 'Archer Warship', 'No', 'East Asian', 'No'),
    (13, 'Cumans', 'Cavalry', 'The last khans', 'No', 'MountedArcher', 'No', 'Central asian', 'No'),
    (14, 'Dravidians', 'Infantry Naval', 'Dynasties of India', 'No', 'Infantry Warship', 'No', 'South Asian', 'Yes'),
    (15, 'Ethiopians', 'Archer', 'The african kingdoms', 'No', 'Infantry', 'No', 'African', 'Yes'),
    (16, 'Franks', 'Cavalry', 'The age of Kings', 'No', 'Infantry', 'No', 'Western European', 'Yes'),
    (17, 'Georgians', 'Defensive Cavalry', 'The mountain Royals', 'No', 'Cavalry', 'Yes', 'Mediterranean', 'Yes'),
    (18, 'Goths', 'Infantry', 'The age of Kings', 'No', 'Infantry', 'No', 'Central European', 'No'),
    (19, 'Gurjaras', 'Cavalry', 'Dynasties of India', 'No', 'Infantry Cavalry', 'Yes', 'South Asian', 'Yes'),
    (20, 'Hindustanis', 'Camel Gunpowder', 'Dynasties of India', 'No', 'Infantry Cavalry', 'Yes', 'South Asian', 'Yes'),
    (21, 'Huns', 'Cavalry', 'The conquerors', 'No', 'Cavalry', 'No', 'Central European', 'No'),
    (22, 'Inca', 'Infantry', 'The forgotten', 'No', 'Infantry Skirmisher', 'Yes', 'Mesoamerican', 'No'),
    (23, 'Italians', 'Archer Naval', 'The forgotten', 'Yes', 'Archer Infantry', 'Yes', 'Mediterranean', 'Yes'),
    (24, 'Japanese', 'Infantry', 'The age of Kings', 'No', 'Infantry', 'Yes', 'East Asian', 'Yes'),
    (25, 'Jurchens', 'Cavalry Gunpowder', 'The three kingdoms', 'No', 'Cavalry Gunpowder', 'No', 'East Asian', 'No'),
    (26, 'Khitans', 'Infantry Cavalry', 'The three kingdoms', 'No', 'Infantry siege', 'No', 'East Asian', 'Yes'),
    (27, 'Khmer', 'Siege Cavalry', 'Rise of the rajas', 'No', 'Cavalry', 'Yes', 'Southeast Asian', 'Yes'),
    (28, 'Koreans', 'Defensive Naval', 'The conquerors', 'No', 'MountedArcher Warship', 'No', 'East Asian', 'Yes'),
    (29, 'Lithuanians', 'Cavalry Monk', 'The last khans', 'No', 'Cavalry', 'Yes', 'Eastern European', 'Yes'),
    (30, 'Magyars', 'Cavalry', 'The forgotten', 'No', 'Cavalry', 'No', 'Eastern European', 'Yes'),
    (31, 'Malay', 'Naval', 'Rise of the rajas', 'No', 'Infantry', 'Yes', 'Southeast Asian', 'Yes'),
    (32, 'Malians', 'Infantry', 'The african kingdoms', 'No', 'Infantry', 'Yes', 'African', 'Yes'),
    (33, 'Maya', 'Archer', 'The conquerors', 'No', 'Archer', 'No', 'Mesoamerican', 'No'),
    (34, 'Mongols', 'Cavalry archer', 'The age of Kings', 'No', 'MounterArcher', 'No', 'East Asian', 'Yes'),
    (35, 'Persians', 'Cavalry', 'The age of Kings', 'No', 'Cavalry', 'No', 'Middle Eastern', 'Yes'),
    (36, 'Poles', 'Cavalry', 'Dawn of the dukes', 'No', 'Infantry Cavalry', 'Yes', 'Eastern European', 'Yes'),
    (37, 'Portuguese', 'Naval Gunpowder', 'The african kingdoms', 'Yes', 'Siege Warship', 'Yes', 'Mediterranean', 'Yes'),
    (38, 'Romans', 'Infantry', 'Return of Rome', 'No', 'Cavalry Infantry', 'Yes', 'Mediterranean', 'No'),
    (39, 'Saracens', 'Cavalry Naval', 'The age of Kings', 'Yes', 'MounterArcher', 'Yes', 'Middle Eastern', 'Yes'),
    (40, 'Shu', 'Archer Siege', 'The three kingdoms', 'No', 'Infantry Siege', 'No', 'East Asian', 'No'),
    (41, 'Sicilians', 'Infantry Cavalry', 'Lords of the west', 'No', 'Infantry', 'No', 'Mediterranean', 'Yes'),
    (42, 'Slavs', 'Infantry Siege', 'The forgotten', 'No', 'Cavalry', 'Yes', 'Eastern European', 'Yes'),
    (43, 'Spanish', 'Gunpowder Monk', 'The conquerors', 'Yes', 'MountedArcher', 'Yes', 'Mediterranean', 'Yes'),
    (44, 'Tatars', 'Cavalry', 'The last khans', 'No', 'Cavalry', 'No', 'Central asian', 'Yes'),
    (45, 'Teutons', 'Infantry', 'The age of Kings', 'No', 'Infantry', 'Yes', 'Central European', 'Yes'),
    (46, 'Turks', 'Gunpowder', 'The age of Kings', 'Yes', 'Gunpowder', 'Yes', 'Middle Eastern', 'Yes'),
    (47, 'Vietnamese', 'Archer', 'Rise of the rajas', 'No', 'Archer', 'No', 'East Asian', 'Yes'),
    (48, 'Vikings', 'Infantry Naval', 'The age of Kings', 'No', 'Infantry Warship', 'No', 'Central European', 'Yes'),
    (49, 'Wei', 'Cavalry', 'The three kingdoms', 'No', 'Cavalry MountedArcher', 'No', 'East Asian', 'No'),
    (50, 'Wu', 'Infantry Naval', 'The three kingdoms', 'No', 'Archer Infantry', 'Yes', 'East Asian', 'No');